module.exports = {
  '': 'code',
  'atom': 'Atom',
  'bash': 'Bash',
  'c': 'C',
  'clike': 'C-like',
  'coffee': 'CoffeeScript',
  'coffeescript': 'CoffeeScript',
  'cpp': 'C++',
  'css': 'CSS',
  'css-extras': 'CSS Extras',
  'diff': 'Diff',
  'git': 'Git',
  'go': 'Go',
  'graphql': 'GraphQL',
  'handlebars': 'Handlebars',
  'haskell': 'Haskell',
  'hs': 'Haskell',
  'html': 'HTML',
  'json': 'JSON',
  'javascript': 'JavaScript',
  'js': 'JavaScript',
  'js-extras': 'JS Extras',
  'jsx': 'JSX',
  'less': 'Less',
  'makefile': 'Makefile',
  'markdown': 'Markdown',
  'mathml': 'MathML',
  'md': 'Markdown',
  'objc': 'Objective C',
  'objectivec': 'Objective C',
  'ocaml': 'OCaml',
  'py': 'Python',
  'python': 'Python',
  'reason': 'Reason',
  'rss': 'RSS',
  'rust': 'Rust',
  'sass': 'Sass',
  'scss': 'Scss',
  'shell': 'Shell',
  'sql': 'SQL',
  'ssml': 'SSML',
  'stylus': 'Stylus',
  'svg': 'SVG',
  'ts': 'TypeScript',
  'tsx': 'TSX',
  'typescript': 'TypeScript',
  'wasm': 'WebAssembly',
  'webmanifest': 'webmanifest',
  'xml': 'XML',
  'yaml': 'YAML',
  'yml': 'YAML',
};